---
- hosts: localhost
  connection: local
  roles:
    #############################################################################
    # Foundational ##############################################################
    #############################################################################

    - role: homebrew
      tags: [foundational, package-and-build, homebrew]

    # Depends on homebrew.
    - role: git
      tags: [foundational, brew-pkg, git]

    # Depends on homebrew.
    - role: gnu-command-line-tools
      tags: [foundational, brew-pkg, gnu-command-line-tools]

    # Depends on homebrew.
    - role: make
      tags: [foundational, package-and-build, brew-pkg, make]

    # Depends on homebrew.
    - role: bash
      tags: [foundational, brew-pkg, programming-languages, bash]

    - role: cmake
      tags: [foundational, package-and-build, bespoke-pkg, cmake]
      vars:
        # https://cmake.org/download/
        cmake_version: "3.19.6"

    - role: python3
      tags: [foundational, programming-languages, bespoke-pkg, python3]
      vars:
        # https://www.python.org/ftp/python/
        python3_version: "3.9.2"
        python3_macos_version: "10.9" # this is used in the .pkg file name.
        python3_version_major_minor: "{{ python3_version | regex_replace('^([0-9]+)\\.([0-9]+)(?:\\.[0-9]+)?$', '\\1.\\2') }}"

    - role: mac-ports
      tags: [foundational, package-and-build, bespoke-pkg, mac-ports]
      vars:
        # https://www.macports.org/install.php
        macports_version: "2.6.4_1"
        macports_mac_release: "11-BigSur"

    - role: node
      tags: [foundational, programming-languages, bespoke-pkg, node]
      vars:
        # https://nodejs.org/dist/
        # https://github.com/nodejs/node/releases
        node_version: "15.11.0"

    - role: maven
      tags: [foundational, package-and-build, brew-pkg, maven]

    - role: llvm
      tags: [foundational, package-and-build, brew-pkg, llvm]

    - role: openssl
      tags: [foundational, package-and-build, brew-pkg, openssl]

    #############################################################################
    # Fonts #####################################################################
    #############################################################################

    - role: font-hack
      tags: [fonts, brew-cask-pkg, font-hack]

    - role: consolas
      tags: [fonts, bespoke-pkg, consolas]

    #############################################################################
    # Configuration #############################################################
    #############################################################################

    - role: ssh-keys
      tags: [configuration, ssh-keys]

    - role: better-touch-tool
      tags: [configuration, bespoke-pkg, better-touch-tool]
      vars:
        # https://folivora.ai/releases
        better_touch_tool_version: "" # using latest

    - role: dotfiles
      tags: [configuration, dotfiles]

    - role: dotemacs
      tags: [configuration, dotemacs]

    #############################################################################
    # Programming languages #####################################################
    #############################################################################

    - role: clojure
      tags: [programming-languages, brew-pkg, clojure]

    - role: java
      tags: [programming-languages, brew-cask-pkg, java]
      vars:
        java_version: adoptopenjdk15

    - role: go
      tags: [programming-languages, bespoke-pkg, go]
      vars:
        # https://dl.google.com/go/go1.16.1.darwin-amd64.pkg
        go_version: "1.16.1"

    - role: rust
      tags: [programming-languages, rust]

    - role: ruby
      tags: [programming-languages, ruby]
      vars:
        ruby_version: 3.0.0

    - role: lua
      tags: [programming-languages, bespoke-pkg, lua]

    - role: luajit
      tags: [programming-languages, bespoke-pkg, luajit]

    - role: octave
      tags: [programming-languages, brew-pkg, octave]

    - role: r
      tags: [programming-languages, bespoke-pkg, r]
      vars:
        r_version: "4.0.4"

    - role: haskell
      tags: [programming-languages, brew-pkg, haskell]

    # DISABLED: `stack install purescript` is currently failing, disabling until
    # I figure it out.
    # https://gist.github.com/mpereira/a2418c458418cd01a2d18301eaeae85e
    - role: purescript
      tags: [disabled, programming-languages, purescript]

    #############################################################################
    # Text editors ##############################################################
    #############################################################################

    - role: build-emacs
      tags: [text-editors, brew-pkg, build-emacs]

    - role: emacs-pre-built
      tags: [text-editors, bespoke-pkg, emacs-pre-built]
      vars:
        emacs_pre_built_version: "27.1"
        emacs_pre_built_patch: "-1"
        # emacs_pre_built_version: "26.1-rc1"
        # emacs_pre_built_pretest: "yes"

    # DISABLED: Vim isn't compiling on macOS Big Sur with LLVM 12, disabling
    # until I figure it out.
    # https://stackoverflow.com/questions/65750657/getting-an-error-on-configuring-vim-uint32-t-check-not-defined-correctly
    - role: vim
      tags: [disabled, text-editors, bespoke-pkg, vim]
      vars:
        vim_version: "8.2"

    - role: neovim
      tags: [text-editors, bespoke-pkg, neovim]
      vars:
        # https://github.com/neovim/neovim/releases
        neovim_version: "0.4.4"

    - role: vscode
      tags: [text-editors, brew-pkg, vscode]

    - role: macvim
      tags: [text-editors, bespoke-pkg, macvim]
      vars:
        # https://github.com/macvim-dev/macvim/releases
        macvim_version: "snapshot-165"

    #############################################################################
    # Behaviors #################################################################
    #############################################################################

    - role: caps-lock-remapped-to-control
      tags: [behaviors, caps-lock-remapped-to-control]

    #############################################################################
    # Security ##################################################################
    #############################################################################

    - role: prey
      tags: [security, bespoke-pkg, prey]
      vars:
        prey_version: "1.9.2"

    - role: vault
      tags: [security, npm-pkg, vault]
      vars:
        vault_version: "0.3.0"

    - role: gnupg
      tags: [security, bespoke-pkg, gnupg]
      vars:
        gnupg_version: "2.2.17"

    ############################################################################
    # Observability ############################################################
    ############################################################################

    - role: glances
      tags: [observability, pip-pkg, glances]

    - role: ngrep
      tags: [observability, brew-pkg, ngrep]

    - role: jmeter
      tags: [observability, brew-pkg, jmeter]

    - role: htop
      tags: [observability, brew-pkg, htop]

    - role: vtop
      tags: [observability, npm-pkg, vtop]

    ############################################################################
    # Data Systems #############################################################
    ############################################################################

    - role: hadoop
      tags: [data-systems, brew-pkg, hadoop]

    ############################################################################
    # Document processing and plotting #########################################
    ############################################################################

    - role: mactex
      tags: [mactex, brew-cask-pkg]

    - role: gnuplot
      tags: [gnuplot, brew-pkg]

    ############################################################################
    # Markup tools #############################################################
    ############################################################################

    - role: grip
      tags: [markup-tools, pip-pkg, grip]

    - role: wkhtmltopdf
      tags: [markup-tools, brew-cask-pkg, wkhtmltopdf]

    - role: hugo
      tags: [markup-tools, brew-pkg, hugo]
      vars:
        # NOTE: version is not actually used because homebrew still can't
        # install a versioned package.
        hugo_version: "0.54.0"

    - role: pandoc
      tags: [markup-tools, brew-pkg, pandoc]

    - role: markdown
      tags: [markup-tools, brew-pkg, markdown]

    ############################################################################
    # Desktop applications #####################################################
    ############################################################################

    - role: grammarly
      tags: [desktop-applications, brew-pkg, grammarly]

    - role: elgato-dock
      tags: [desktop-applications, bespoke-pkg, elgato-dock]
      vars:
        elgato_dock_version: "1.2.10.131_40"

    - role: istat-menus
      tags: [desktop-applications, brew-cask-pkg, istat-menus]

    - role: sound-control
      tags: [desktop-applications, brew-cask-pkg, sound-control]

    - role: pdf-expert
      tags: [desktop-applications, brew-cask-pkg, pdf-expert]

    - role: flux
      tags: [desktop-applications, brew-cask-pkg, flux]

    - role: toggle-dark-mode
      tags: [desktop-applications, toggle-dark-mode]

    - role: cursorcerer
      tags: [desktop-applications, brew-cask-pkg, cursorcerer]

    - role: licecap
      tags: [desktop-applications, bespoke-pkg, licecap]
      vars:
        licecap_version: "" # not configurable at the moment

    - role: unity-hub
      tags: [desktop-applications, bespoke-pkg, unity-hub]

    - role: unity
      tags: [desktop-applications, bespoke-pkg, unity]
      vars:
        unity_version: "2021.2.0a8"

    - role: xquartz
      tags: [desktop-applications, bespoke-pkg, xquartz]
      vars:
        xquartz_version: "2.7.11"

    - role: rescuetime
      tags: [desktop-applications, bespoke-pkg, rescuetime]

    # TODO: upgrade to xbar: https://github.com/matryer/xbar/issues/607.
    - role: bitbar
      tags: [desktop-applications, bespoke-pkg, bitbar]
      vars:
        bitbar_version: "1.10.1"

    - role: bitbar-plugins
      tags: [desktop-applications, bitbar, bitbar-plugins]

    - role: divvy
      tags: [desktop-applications, bespoke-pkg, divvy]

    - role: android-file-transfer
      tags: [desktop-applications, bespoke-pkg, android-file-transfer]

    - role: dropbox
      tags: [desktop-applications, bespoke-pkg, dropbox]

    - role: google-chrome
      tags: [desktop-applications, bespoke-pkg, google-chrome]

    - role: firefox
      tags: [desktop-applications, bespoke-pkg, firefox]
      vars:
        firefox_version: "latest"

    - role: google-chrome-as-default-browser
      tags: [desktop-applications, google-chrome-as-default-browser]

    - role: skype
      tags: [desktop-applications, bespoke-pkg, skype]

    - role: slack
      tags: [desktop-applications, bespoke-pkg, slack]

    - role: spotify
      tags: [desktop-applications, bespoke-pkg, spotify]

    - role: steam
      tags: [desktop-applications, bespoke-pkg, steam]

    - role: teensy-loader
      tags: [desktop-applications, bespoke-pkg, teensy-loader]

    - role: ynab
      tags: [desktop-applications, bespoke-pkg, ynab]
      vars:
        ynab_version: "4.3.855"

    - role: google-photos
      tags: [desktop-applications, bespoke-pkg, google-photos]

    - role: dash
      tags: [desktop-applications, bespoke-pkg, dash]

    - role: persephone
      tags: [desktop-applications, bespoke-pkg, persephone]
      vars:
        persephone_version: 0.18.0-alpha

    - role: vlc
      tags: [desktop-applications, bespoke-pkg, vlc]
      vars:
        # http://download.videolan.org/pub/videolan/vlc/
        vlc_version: "3.0.12"

    #############################################################################
    # Programming utilities #####################################################
    #############################################################################

    - role: rust-analyzer
      tags: [programming-utilities, brew-pkg, rust-analyzer]

    - role: clojure-lsp
      tags: [programming-utilities, bespoke-pkg, clojure-lsp]

    - role: black
      tags: [programming-utilities, pip-pkg, black]

    - role: ktlint
      tags: [programming-utilities, bespoke-pkg, ktlint]

    - role: ctags
      tags: [programming-utilities, brew-pkgm ctags]

    - role: gron
      tags: [programming-utilities, bespoke-pkg, gron]
      vars:
        gron_version: "0.6.1"

    - role: yapf
      tags: [programming-utilities, pip-pkg, yapf]

    - role: prettier
      tags: [programming-utilities, npm-pkg, prettier]

    - role: node-cljfmt
      tags: [programming-utilities, npm-pkg, node-cljfmt]

    - role: yq
      tags: [programming-utilities, bespoke-pkg, yq]

    - role: shfmt
      tags: [programming-utilities, brew-pkg, shfmt]

    - role: pyre-check
      tags: [programming-utilities, pip-pkg, pyre-check]

    - role: shellcheck
      tags: [programming-utilities, brew-pkg, shellcheck]

    #############################################################################
    # Shell #####################################################################
    #############################################################################

    - role: babashka
      tags: [shell, bespoke-pkg, babashka]

    - role: zsh
      tags: [shell, brew-pkg, zsh]

    - role: fish
      tags: [shell, brew-pkg, fish]

    - role: fish-foreign-env
      tags: [shell, bespoke-pkg, fish, fish-foreign-env]

    - role: iterm
      tags: [shell, brew-cask-pkg, iterm]

    - role: tmux
      tags: [shell, brew-pkg, tmux]

    - role: tmuxinator
      tags: [shell, gem-pkg, tmux, tmuxinator]

    #############################################################################
    # Package managers and build tools ##########################################
    #############################################################################

    - role: yarn
      tags: [package-and-build, brew-pkg, yarn]

    - role: pulp
      tags: [package-and-build, npm-pkg, pulp]

    - role: bundler
      tags: [package-and-build, gem-pkg, bundler]

    - role: graalvm
      tags: [package-and-build, bespoke-pkg, graalvm]
      vars:
        graalvm_version: "21.0.0.2"

    # NOTE: depends on 'java'.
    - role: leiningen
      tags: [package-and-build, brew-pkg, leiningen]

    #############################################################################
    # Virtualization, provisioning, containers and system tools #################
    #############################################################################

    - role: openzfs
      tags: [system-tools, brew-cask-pkg, openzfs]

    - role: virtualbox
      tags: [system-tools, bespoke-pkg, virtualbox]
      vars:
        # Wait until Vagrant fixes this issue before upgrading to 5.2
        # https://github.com/hashicorp/vagrant/issues/9090
        # virtualbox_version: "5.2.0"
        # virtualbox_build: "118431"
        virtualbox_version: "6.0.2"
        virtualbox_build: "128162"

    - role: vagrant
      tags: [system-tools, bespoke-pkg, vagrant]
      vars:
        vagrant_version: "2.2.14"

    - role: vagrant-vbguest
      tags: [system-tools, vagrant-pkg, vagrant, vagrant-vbguest]
      vars:
        vagrant_vbguest_version: "0.29.0"

    - role: docker
      tags: [system-tools, brew-cask-pkg, docker]

    - role: terraform
      tags: [system-tools, bespoke-pkg, terraform]
      vars:
        terraform_version: "0.14.8"
        terraform_checksum: "sha256:30115a2ee5f61178527089d8e5da20053927b364b08dc7aee6894a162ccbd793"

    - role: kubectl
      tags: [system-tools, bespoke-pkg, kubernetes, kubectl]
      vars:
        kubectl_version: "1.20.0"

    - role: krew
      tags: [system-tools, bespoke-pkg, kubernetes, krew]

    - role: kubectl-tree
      tags: [system-tools, krew-pkg, kubernetes, kubectl-tree]

    ############################################################################
    # Browser plugins ##########################################################
    ############################################################################

    - role: firefox-adblock-plus
      tags: [bespoke-pkg, firefox-adblock-plus]

    ############################################################################
    # Multimedia ###############################################################
    ############################################################################

    - role: beets
      tags: [multimedia, pip-pkg, beets]

    - role: ffmpeg
      tags: [multimedia, brew-pkg, ffmpeg]

    - role: imagemagick
      tags: [multimedia, brew-pkg, imagemagick]

    - role: gifsicle
      tags: [multimedia, brew-pkg, gifsicle]

    - role: mpg123
      tags: [multimedia, brew-pkg, mpg123]

    - role: mpd
      tags: [multimedia, brew-pkg, mpd]

    - role: mpc
      tags: [multimedia, brew-pkg, mpc]

    - role: mpdscribble
      tags: [multimedia, brew-pkg, mpdscribble]

    - role: shpotify
      tags: [multimedia, brew-pkg, shpotify]

    - role: mplayer
      tags: [multimedia, brew-pkg, mplayer]

    - role: taglib
      tags: [multimedia, brew-pkg, taglib]

    #############################################################################
    # Command line tools ########################################################
    #############################################################################

    - role: pngpaste
      tags: [command-line-tools, brew-pkg, pngpaste]

    - role: git-delta
      tags: [command-line-tools, brew-pkg, git-delta]

    - role: xz
      tags: [command-line-tools, brew-pkg, xz]

    - role: p7zip
      tags: [command-line-tools, brew-pkg, p7zip]

    - role: awscli
      tags: [command-line-tools, pip-pkg, awscli]

    # DISABLED: using awscli instead.
    - role: s3cmd
      tags: [disabled, command-line-tools, s3cmd]

    - role: defaultbrowser
      tags: [command-line-tools, git-pkg, defaultbrowser]
      vars:
        defaultbrowser_version: "1.1"

    - role: jq
      tags: [command-line-tools, bespoke-pkg, jq]

    - role: tree
      tags: [command-line-tools, brew-pkg, tree]

    - role: pgsanity
      tags: [command-line-tools, pip-pkg, pgsanity]

    - role: ripgrep
      tags: [command-line-tools, brew-pkg, ripgrep]

    - role: fd
      tags: [command-line-tools, brew-pkg, fd]

    - role: tealdeer
      tags: [command-line-tools, cargo-pkg, tealdeer]

    - role: wrk
      tags: [command-line-tools, brew-pkg, wrk]

    - role: websocat
      tags: [command-line-tools, bespoke-pkg, websocat]

    - role: terminal-notifier
      tags: [command-line-tools, brew-pkg, terminal-notifier]

    #############################################################################
    # Miscellaneous #############################################################
    #############################################################################

    # DISABLED: this was only necessary to build Cantata I think?
    - role: qt5
      tags: [disabled, bespoke-pkg, qt5]
      vars:
        qt_major_minor_version: "5.12"
        qt_version: "{{ qt_major_minor_version }}.0"

    - role: fontforge
      tags: [brew-pkg, fontforge]

    # Depends on xquartz.
    - role: wordnet
      tags: [brew-pkg, wordnet]
